// A realistic shelf: ~40 games with SteamSpy-shaped tag lists (top ~15, most
// voted first — so "Singleplayer", "Indie", "Action", "Adventure" are on
// nearly everything), playtime and recent minutes the way a real account
// looks: a couple of monsters, a long tail of never-launched sale purchases.
import type { PickerGame } from "@/lib/recommend";

const g = (appid: number, name: string, playtimeMin: number, recentMin: number, tags: string[]): PickerGame => ({ appid, name, playtimeMin, recentMin, tags });

export const REAL: PickerGame[] = [
  g(1086940, "Baldur's Gate 3", 9120, 620, ["RPG", "Choices Matter", "Story Rich", "Character Customization", "Turn-Based Combat", "CRPG", "Dungeons & Dragons", "Adventure", "Fantasy", "Party-Based RPG", "Co-op", "Singleplayer", "Multiplayer", "Romance", "Strategy"]),
  g(1245620, "Elden Ring", 7300, 0, ["Souls-like", "Dark Fantasy", "Open World", "RPG", "Difficult", "Action RPG", "Third Person", "Fantasy", "Singleplayer", "Great Soundtrack", "Atmospheric", "Multiplayer", "Co-op", "Action", "Violent"]),
  g(367520, "Hollow Knight", 2100, 0, ["Metroidvania", "Souls-like", "Platformer", "Great Soundtrack", "Atmospheric", "Difficult", "Exploration", "2D", "Indie", "Singleplayer", "Hand-drawn", "Dark", "Adventure", "Action", "Story Rich"]),
  g(1091500, "Cyberpunk 2077", 410, 0, ["Cyberpunk", "Open World", "RPG", "Story Rich", "Futuristic", "Singleplayer", "Sci-fi", "Atmospheric", "FPS", "Nudity", "Character Customization", "First-Person", "Mature", "Action", "Adventure"]),
  g(1174180, "Red Dead Redemption 2", 3400, 0, ["Open World", "Story Rich", "Western", "Adventure", "Multiplayer", "Realistic", "Singleplayer", "Atmospheric", "Action", "Third Person", "Shooter", "Beautiful", "Great Soundtrack", "Mature", "Horses"]),
  g(105600, "Terraria", 4300, 0, ["Sandbox", "Survival", "2D", "Adventure", "Crafting", "Multiplayer", "Building", "Open World", "Pixel Graphics", "Co-op", "Exploration", "Indie", "Singleplayer", "RPG", "Online Co-Op"]),
  g(292030, "The Witcher 3: Wild Hunt", 6100, 0, ["Open World", "RPG", "Story Rich", "Atmospheric", "Mature", "Fantasy", "Adventure", "Choices Matter", "Singleplayer", "Third Person", "Nudity", "Great Soundtrack", "Dark Fantasy", "Action", "Medieval"]),
  g(1145360, "Hades", 3900, 180, ["Roguelike", "Action Roguelike", "Indie", "Action", "Hack and Slash", "Mythology", "Story Rich", "Great Soundtrack", "Isometric", "Roguelite", "Dungeon Crawler", "Singleplayer", "Difficult", "Fast-Paced", "Replay Value"]),
  g(271590, "Grand Theft Auto V", 1200, 0, ["Open World", "Action", "Multiplayer", "Crime", "Automobile Sim", "Third Person", "Mature", "Singleplayer", "Shooter", "First-Person", "Adventure", "Racing", "Co-op", "Comedy", "Funny"]),
  g(413150, "Stardew Valley", 5400, 400, ["Farming Sim", "Life Sim", "Pixel Graphics", "Relaxing", "RPG", "Multiplayer", "Casual", "Simulation", "Sandbox", "Indie", "Crafting", "Singleplayer", "Co-op", "Cute", "Building"]),
  g(1966720, "Lethal Company", 2600, 90, ["Online Co-Op", "Horror", "Co-op", "Multiplayer", "Psychological Horror", "Survival Horror", "Comedy", "First-Person", "Funny", "Sci-fi", "Space", "Exploration", "Indie", "Atmospheric", "Action"]),
  g(646570, "Slay the Spire", 6800, 300, ["Card Game", "Roguelike Deckbuilder", "Roguelike", "Deckbuilding", "Strategy", "Turn-Based", "Singleplayer", "Indie", "Replay Value", "Difficult", "Turn-Based Strategy", "Dungeon Crawler", "Pixel Graphics", "2D", "Fantasy"]),
  g(2379780, "Balatro", 1900, 260, ["Card Game", "Roguelike Deckbuilder", "Deckbuilding", "Roguelike", "Casual", "Singleplayer", "Indie", "Strategy", "Replay Value", "Turn-Based", "Poker", "Addictive", "Relaxing", "Pixel Graphics", "2D"]),
  g(1817070, "Marvel's Spider-Man Remastered", 60, 0, ["Superhero", "Open World", "Action", "Adventure", "Singleplayer", "Third Person", "Story Rich", "Great Soundtrack", "Beautiful", "Atmospheric", "Comic Book", "Exploration", "Cinematic", "Parkour", "Combat"]),
  g(1237970, "Titanfall 2", 0, 0, ["FPS", "Mechs", "Multiplayer", "Shooter", "Singleplayer", "Action", "First-Person", "Story Rich", "Parkour", "Sci-fi", "Fast-Paced", "Great Soundtrack", "Robots", "Online Co-Op", "PvP"]),
  g(1938090, "Call of Duty", 0, 0, ["FPS", "Multiplayer", "Shooter", "Action", "First-Person", "PvP", "Military", "Online Co-Op", "War", "Co-op", "Singleplayer", "Battle Royale", "Free to Play", "Realistic", "Zombies"]),
  g(1172470, "Apex Legends", 480, 0, ["Free to Play", "Battle Royale", "Multiplayer", "Shooter", "FPS", "Hero Shooter", "First-Person", "Action", "PvP", "Team-Based", "Online Co-Op", "Fast-Paced", "Sci-fi", "Competitive", "Co-op"]),
  g(1966900, "Dredge", 0, 0, ["Fishing", "Lovecraftian", "Horror", "Exploration", "Atmospheric", "Adventure", "Singleplayer", "Indie", "Relaxing", "Story Rich", "Psychological Horror", "Open World", "Mystery", "Management", "Boating"]),
  g(1332010, "Stray", 0, 0, ["Cats", "Adventure", "Cyberpunk", "Atmospheric", "Exploration", "Singleplayer", "Post-apocalyptic", "Puzzle", "Story Rich", "Cute", "Sci-fi", "Third Person", "Emotional", "Beautiful", "Indie"]),
  g(1817190, "Marvel's Spider-Man: Miles Morales", 0, 0, ["Superhero", "Open World", "Action", "Adventure", "Singleplayer", "Third Person", "Story Rich", "Parkour", "Combat", "Beautiful", "Comic Book", "Great Soundtrack", "Exploration", "Cinematic", "Atmospheric"]),
  g(1426210, "It Takes Two", 380, 0, ["Co-op", "Local Co-Op", "Online Co-Op", "Adventure", "Puzzle", "Platformer", "Multiplayer", "Split Screen", "Story Rich", "Action", "3D Platformer", "Funny", "Comedy", "Colorful", "Cartoon"]),
  g(1229490, "Ultrakill", 150, 0, ["FPS", "Fast-Paced", "Action", "Shooter", "Retro", "Difficult", "Character Action Game", "Great Soundtrack", "Gore", "Singleplayer", "Indie", "First-Person", "Robots", "Old School", "Boomer Shooter"]),
  g(881100, "Noita", 90, 0, ["Roguelike", "Pixel Graphics", "Physics", "Difficult", "Magic", "Action Roguelike", "Exploration", "Singleplayer", "Indie", "Sandbox", "Roguelite", "2D", "Procedural Generation", "Perma Death", "Open World"]),
  g(1284210, "Guild Wars 2", 0, 0, ["MMORPG", "Massively Multiplayer", "Fantasy", "Free to Play", "Open World", "RPG", "Adventure", "Multiplayer", "Character Customization", "PvP", "Exploration", "Story Rich", "Co-op", "Action", "MMO"]),
  g(289070, "Sid Meier's Civilization VI", 1500, 0, ["Turn-Based Strategy", "Strategy", "4X", "Turn-Based", "Historical", "Grand Strategy", "Multiplayer", "Singleplayer", "Management", "Tactical", "City Builder", "Resource Management", "Base Building", "Simulation", "Replay Value"]),
  g(255710, "Cities: Skylines", 0, 0, ["City Builder", "Simulation", "Building", "Management", "Strategy", "Sandbox", "Singleplayer", "Moddable", "Relaxing", "Economy", "Realistic", "Resource Management", "Base Building", "Casual", "Open World"]),
  g(632470, "Disco Elysium", 240, 0, ["Story Rich", "RPG", "Choices Matter", "Detective", "Isometric", "CRPG", "Singleplayer", "Great Soundtrack", "Narrative", "Atmospheric", "Text-Based", "Mystery", "Investigation", "Mature", "Political"]),
  g(261570, "Ori and the Blind Forest", 30, 0, ["Metroidvania", "Platformer", "Great Soundtrack", "Beautiful", "Atmospheric", "Singleplayer", "2D", "Adventure", "Difficult", "Emotional", "Indie", "Exploration", "Story Rich", "Precision Platformer", "Fantasy"]),
  g(1113560, "NieR Replicant", 0, 0, ["Story Rich", "Action RPG", "JRPG", "Great Soundtrack", "RPG", "Anime", "Singleplayer", "Emotional", "Hack and Slash", "Post-apocalyptic", "Female Protagonist", "Atmospheric", "Action", "Adventure", "Mature"]),
  g(524220, "NieR:Automata", 1700, 0, ["Great Soundtrack", "Story Rich", "Action", "RPG", "Post-apocalyptic", "Female Protagonist", "Anime", "Hack and Slash", "Open World", "Singleplayer", "Atmospheric", "Action RPG", "JRPG", "Philosophical", "Sci-fi"]),
  g(1599340, "Lost Ark", 45, 0, ["MMORPG", "Free to Play", "Action RPG", "Hack and Slash", "Massively Multiplayer", "Isometric", "RPG", "Multiplayer", "Fantasy", "Action", "PvE", "Loot", "Co-op", "Adventure", "Dungeon Crawler"]),
  g(1888930, "The Last of Us Part I", 0, 0, ["Story Rich", "Post-apocalyptic", "Survival", "Zombies", "Singleplayer", "Third Person", "Action", "Adventure", "Atmospheric", "Horror", "Emotional", "Survival Horror", "Cinematic", "Mature", "Stealth"]),
  g(1902490, "Peglin", 20, 0, ["Roguelike", "Pinball", "Roguelite", "Casual", "Deckbuilding", "Turn-Based", "Singleplayer", "Indie", "Pixel Graphics", "Strategy", "2D", "Fantasy", "Cute", "Replay Value", "Physics"]),
  g(1794680, "Vampire Survivors", 1400, 0, ["Bullet Hell", "Roguelite", "Pixel Graphics", "Casual", "Action Roguelike", "Roguelike", "Singleplayer", "Indie", "Retro", "2D", "Arcade", "Addictive", "Replay Value", "Loot", "Horror"]),
  g(1097150, "Fall Guys", 300, 0, ["Multiplayer", "Battle Royale", "Party Game", "Funny", "Casual", "Platformer", "Free to Play", "Colorful", "Cute", "Online Co-Op", "PvP", "Physics", "3D Platformer", "Family Friendly", "Racing"]),
  g(945360, "Among Us", 600, 0, ["Multiplayer", "Online Co-Op", "Social Deduction", "Party Game", "Casual", "Funny", "Space", "Co-op", "2D", "Indie", "Psychological", "Cartoony", "Cute", "Strategy", "Team-Based"]),
  g(1938010, "Subnautica: Below Zero", 0, 0, ["Survival", "Open World", "Underwater", "Exploration", "Crafting", "Adventure", "Singleplayer", "Atmospheric", "Base Building", "Sci-fi", "Sandbox", "Story Rich", "First-Person", "Building", "Relaxing"]),
  g(264710, "Subnautica", 2200, 0, ["Open World Survival Craft", "Survival", "Underwater", "Exploration", "Open World", "Crafting", "Adventure", "Singleplayer", "Atmospheric", "Base Building", "Sci-fi", "Sandbox", "Horror", "First-Person", "Story Rich"]),
  g(1817230, "Hi-Fi RUSH", 0, 0, ["Rhythm", "Action", "Hack and Slash", "Great Soundtrack", "Character Action Game", "Colorful", "Music", "Singleplayer", "Stylized", "Comedy", "Cartoon", "Funny", "Third Person", "Anime", "Cel-shaded"]),
  g(413410, "Danganronpa", 0, 0, ["Visual Novel", "Anime", "Mystery", "Story Rich", "Detective", "Psychological", "Singleplayer", "Murder Mystery", "Dark", "Adventure", "Great Soundtrack", "Investigation", "Choices Matter", "Puzzle", "Gore"]),
  g(1817090, "Persona 5 Royal", 0, 0, ["JRPG", "Anime", "Story Rich", "Turn-Based Combat", "RPG", "Great Soundtrack", "Singleplayer", "Stylized", "Turn-Based", "Dating Sim", "Party-Based RPG", "Life Sim", "Mystery", "Choices Matter", "Cute"]),
];
